version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    networks:
      - backend
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - CORS_ORIGIN_URL=${CORS_ORIGIN_URL}
      - NODE_ENV=production
    networks:
      - backend

networks:
  backend:
    driver: bridge