version: "3.9"
services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        - API_HOST=${API_HOST}

  server:
    build:
      context: ../server
      dockerfile: Dockerfile

  db:
    build:
      context: ../database
      dockerfile: Dockerfile
