version: '3.9'
services:
  client:
    build:
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=${API_HOST}
    volumes:
      - ../client/src:/usr/src/app/src
      - ../client/package.json:/usr/src/app/package.json
      - ../client/yarn.lock:/usr/src/app/yarn.lock

  server:
    build:
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ../server/src:/usr/src/app/src
      - ../server/package.json:/usr/src/app/package.json
      - ../server/yarn.lock:/usr/src/app/yarn.lock