version: '3.9'
services:
  server:
    image: swenggroup20/cryptocurrency-centralisation-visualisation-server:latest
    container_name: cryptocurrency-centralisation-visualisation-server
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN_URL=${CORS_ORIGIN_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - network
    depends_on:
      - db

  db:
    image: swenggroup20/cryptocurrency-centralisation-visualisation-database:latest
    container_name: cryptocurrency-centralisation-visualisation-database
    build:
      context: ../database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network
    volumes:
      - database_data:/var/lib/postgresql/data

networks:
  network:
    name: cryptocurrency-centralisation-visualisation-network
    driver: bridge

volumes:
  database_data:
    name: cryptocurrency-centralisation-visualisation-database-data
