version: '3.9'
services:
  client:
    image: cryptocurrency-centralisation-visualisation-client
    container_name: cryptocurrency-centralisation-visualisation-client
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - API_HOST=${API_HOST}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
