version: '3.9'
services:
  client:
    image: cryptocurrency-centralisation-visualisation-client
    container_name: cryptocurrency-centralisation-visualisation-client
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true